### ISSUE TITLE
I can't reinstall the modloader

### ISSUE THREAD

**Issue by Bwazaaah** [xforce/anno1800-mod-loader#99] opened 2021-09-02 10:16 UTC
Hello there,

Yesterday, when I tried to launch Anno after the last update, I got a message stating that the mods weren't compatibles with this new version. I tried to update the modloadter, but for unknown reason it failed and I got the same message again and again. So I uninstalled the modloader, and tried to reinstall it. However, when I extract the files in the Win 64 file, the modloader.exe doesn't appear. I reinstalled VS 2019 Redist, but it still don't work.
I'm pretty sure I'm doing something wrong, but I can't find out what it is.

Thanks for your answers !

**Comment by jaygotony** [comment] 2021-09-03 14:39
我發生了類似的問題，
而且更新後我回到 V11版( SHOCK)
不過我透過 UBISOFT內建的遊戲驗證系統，重新驗證遊戲完整性，
然後取代錯誤部分，最後重新更新缺失的部分。
再把 0.8.2 檔案放置回去，就正常可以啟動沒有跳錯誤訊息了
你可以試試看
-----------------------------------------------------------------

I had a similar problem,
It show that I need a update to play the game.
And after the update, It returned back to the V11 version (SHOCK)
However, I re-verified the integrity of the game through the built-in game verification system of UBISOFT.
Then replace the error parts and finally re-update the game.
Put the 0.8.2 file back again, and it will start normally without any error message.
You can try

**Comment by anno2021** [comment] 2021-09-04 15:53
Hi there
I don't know who supposed to do something about this situation, but it happens too frequently - I had to go trough this process at least four times since the V12 update (ie. got update from UBI, version screwed, verify files, fix corrupted ones, redownload High Life DLC, update modloader again). Every time you add or remove a mod it happens, but happened even without it too for no apparent reason. Is modding over for Anno 1800?

**Comment by d0x7** [comment] 2021-09-05 05:41
And I thought it's just me... Was on 0.8, "incompatible, wanna report on github?", then after restart I had to download the files AGAIN (7th time I guess, the 2,2gb patch) and patched 0.8.2. Then got in a loop, with the same "you wanna report", after closing the game launched by itself and after fully closing and opening ubi again, I could start it now, without a error message. Super, super weird. 

I'd like to provide any information needed to address this issue but I don't think the issue is on my side, as there are numerous users with this issue. Same as @jaygotony I got also dumped on a lower version, where high life was "not yet available", days after it's launch soo it has to be G11.

**Comment by xforce** [comment] 2021-09-06 12:19
Ubisoft Connect currently has a bug that causes the game to downgrade for some players.
That is 100% out of my control.
Given that, I don't see any actionable info here for me.

**Closed by xforce** 2021-09-06 12:19 UTC

**Comment by d0x7** [comment] 2021-09-06 12:22
That's good to know, but for me it only happend when I used the modloader. But, as you said, I could imagine this still being a issue on Ubis side, e.g. they detect the modified dlls and think it's because the latest update is not applied or something. They also removed the "modding detected" so they definitely changed *something* in that direction, I think.
