### ISSUE TITLE
Mod-Loader Needs Update for New DLC 12 release 8 dec 2022

### ISSUE THREAD

**Issue by jacquesmail2** [xforce/anno1800-mod-loader#181] opened 2022-12-08 20:16 UTC
Mod-Loader Needs Update for New DLC 12 release 8 dec 2022

I know it might take time, Will Wait. Thanks
Also want to say great Work for all the Updates in the Past. Its been Great.

**Comment by auddie2015** [comment] 2022-12-08 20:50
Next post down he said he is working on it.

**Comment by jasonbuff** [comment] 2022-12-08 21:33
doesnt look like will get it today prolly have to wait till tommorrow or longer

**Comment by xforce** [comment] 2022-12-08 21:34
Duplicate of #180

**Closed by xforce** 2022-12-08 21:34 UTC
