### ISSUE TITLE
Version 0.7.10 is incompatible

### ISSUE THREAD

**Issue by Pankraz01** [xforce/anno1800-mod-loader#60] opened 2020-08-10 14:26 UTC
Version 0.7.10 is incompatible with the new Version 10.08.2020

**Comment by xforce** [comment] 2020-08-10 15:44
Due to the lack of a game update, this is a duplicate of #51 
Last game update was June 17. (Game Update 8.1) which is still compatible.

**Closed by xforce** 2020-08-10 15:44 UTC
