### ISSUE TITLE
8.13 Not working anno 1800

### ISSUE THREAD

**Issue by Bobzilla322** [xforce/anno1800-mod-loader#120] opened 2022-02-15 22:28 UTC
Just happened about 4 hrs ago wont load mods now says game not compatible with this version. Any help would be freaking awesome!

**Comment by seanrdmedia** [comment] 2022-02-16 00:14
also having same problem, absolutely gutted right now!

**Comment by xforce** [comment] 2022-02-16 00:24
Duplicate of #117

**Closed by xforce** 2022-02-16 00:24 UTC
