### ISSUE TITLE
Test that all the XML operations are working as expected.

### ISSUE THREAD

**Issue by xforce** [xforce/anno1800-mod-loader#5] opened 2019-05-16 18:52 UTC
I only did some small basic tests, it is looking good so far.
I know the merge op probably doesn't work 100% as expected, but that is not finished yet anyways, but does a good enough job for basic things.

**Comment by kskudlik** [comment] 2019-05-17 17:11
For me, the replace isn´t working when trying to replace whole XML files. The "#0-replace-entire-file" is crashing my game. Other modifications worked so far.

Also a little request: I think the tool should just go ahead and replace the XML when no ModOps are found.

PS: Thanks a lot for your work it is much appreciated. Being able to load all new things into the game is plain awesome. Later I´m going to try to include new GUIDs if that will working modding to going to be big in 1800

**Comment by xforce** [comment] 2019-05-17 17:48
Thanks for testing.
I was actually thinking about just replacing the file when no ModOps are found earlier today.
I will check out the crash later tonight.

**Comment by xforce** [comment] 2019-05-18 16:57
@kskudlik 
The replace-entire-file case should be fixed now.
I also did some other fixes today.

1b361b7ee7d4eae758284f30fd841b7a543c3f7a
2461f1b723bebf82c5ce5b94f70d49ce333d38b9
c27531cb5c24e740ec6b141827d94194d2af0571
a2dd273c1bcf5db96bcce4810c79e653dfb68c65

I will be writing some actual tests now that have operations with input and expected output and will integrate that in CI, so I don't break it again.

**Comment by kskudlik** [comment] 2019-05-18 19:08
@xforce can confirm that the replace is now working as intended.
although the example isn´t really changing anything which can confuse users: addressed in #14  

it´s even working with the big assets.xml which immediately makes all current mods compatible with 4 lines of XML. Thats plain awesome.

just two minor things:
- I noticed that the mod-loader doesn't forgive any XML errors which the original anno did in most cases, but I don't really think that that´s an issue. as I think you already planed some error log as user feedback for some time in the future. -> Users just need to make sure that their xmls are 100% working.
- when using  in xml it does crash. that could become an issue because anno itself uses them(ex. camera.xml (and because they are helpful : D) But not an urgent thing either.

**Comment by kskudlik** [comment] 2019-05-18 19:18
Are you still planning to skip the xml work and just load the file when there are no ModOps?
On one side it would make things a little more accessible but on the other hand, users might not try to use the xml features at all, because they seem to difficult.

Today extracted some existing Modstuff out off the assets.xml into ModOps and needless to say thats a pain in the butt. Maybe a helper tool which does the comparison between the xml files and creates those modops would be a good solution for that. But also a lot of work obviously.
I´ll think about that a little more tomorrow maybe that's something that i´ll look into creating if there is no better solution.

**Comment by xforce** [comment] 2019-05-18 19:56
@kskudlik Thanks for the feedback, I am a bit hesitant to just offer replace because I would like to encourage use of the XML operations as that does allow using more than one mod in most cases.  

About the comments, that should be handled by libxml2, it can parse the comments in recover mode, which is what I am using, but I could see there being a few issues, maybe it's a good idea to remove comments from the parse tree before doing any operations?! Not sure...

I definitely can see that doing bigger mods is a bit more work with the xml operations at least in the way they are right now, which was just me quickly thinking about the most useful operations to get something done. I was also thinking about having a tool in the future that helps creating those, but not sure how much time I have available to work on something like that (So if we end up deciding that it's the best way to go, outside help would be crucial).
But as mentioned in the README I am open to discussing more operations, or doing some other things to make creating mods easier. 
I could also imagine that starting out with the mod ops is easier than porting existing assets.xml changes, but I haven't done any actual mods with quickbms etc, myself.

Logging is coming very soon, I was even thinking about maybe adding some in-game text overlay thing that shows the errors, because some may not be actual errors but just warnings caused by something and could be fine, that would be something that can be enabled/disabled in some setting somewhere.

But ye thank you very much for the feedback, I really appreciate it.

**Comment by kskudlik** [comment] 2019-05-19 13:20
yeah, I know what you mean. to use multiple mods XML operation is a must and should be encouraged.

Another thing i thought about today is adding a GUID identifler like
`     <ModOp Type="add" GUID="102145">`
which uses Path //Asset[Values/Standard/GUID='102145']
but with a litte twist. I would be great to do the same operation on multiple GUIDs. Like:
`<ModOp Type="add" GUID="102145,102146,102147,102148">`

For example in the mod from DaLexy he replaces the StrackLimit of many GUIDs. So it requieres about 30 of those:
```
<ModOp Type="replace" Path="//Asset[Values/Standard/GUID='101364']/Values/ItemContainer/StackLimit">
		<StackLimit>75</StackLimit>
	</ModOp>
```
with just another GUID. 

Istead using that:
> <ModOp Type="replace" GUID="101364,101365,101366,101367" Path="Values/ItemContainer/StackLimit">
> 		<StackLimit>75</StackLimit>
> 	</ModOp>
would simplify things a lot.

Today i started doing xml comparison - original assets vs modded assets with python which is tedious.
But just a few minutes ago i found: https://github.com/Shoobx/xmldiff which outputs something like:
```
[insert-attribute, /document/story/app:section[4], title, "Signing Bonus"]
[update-attribute, /document/story/app:section[5], ref, "4"]
[update-attribute, /document/story/app:section[5], single-ref, "4"]
```
That could obiviosly be used to rewrite it a simple ModOps HYPE.

While typing the program is doing its stuff on the assets xml. After over 5 mins now it´s still running.
But i´m optimistic that there is a good way to do this.

**Comment by kskudlik** [comment] 2019-05-19 15:49
fyi:  https://github.com/Shoobx/xmldiff is off the table now. takes 20min in "faster" mode which supplies not so good results and over an hour in normal mode.
I going to look into something else. seems like c# would be a faster option

**Comment by xforce** [comment] 2019-05-19 17:46
Thanks for looking into it so quickly.
The GUID thing sounds like a nice addition, should be easy to implement.

**Comment by kskudlik** [comment] 2019-05-19 18:09
looks like you weren´t sitting on your hands either. version checking is always nice. great work.
I´m currently doing some smart home stuff for someone in my family. messin' with amazon dash buttons, Alexa remote control and so on.. 
I´m going to look into the XML compare stuff again in a few.

**Comment by xforce** [comment] 2019-05-20 21:10
The discussed GUID helper property has been implemented in eb67bca540480fa304d103b8f867e044d29fa0b4

**Comment by kskudlik** [comment] 2019-05-22 23:09
as mentioned earlier I thought about how to ease adding new guids using the mod-loader.

At the moment adding a new guid works like:
```
<ModOp Type="add" Path="//Assets[Asset/Values/Standard/GUID='100855']">
<Asset>
            <Template>SlotFactoryBuilding7</Template>
            <Values>
                <Standard>
                    <Name>Clay_Cover</Name>
                    <GUID>901000</GUID>
.....
```
this adds a new asset with GUID 901000 at the same assets node where the asset with GUID 100855 is defined.
At the moment the game has 53841 GUIDs in use, but regardless it´s quite easily possible that different modders use the same GUID for a new asset which of course is a problem when using multiple mods.

So I thought about doing something like:
```
<ModOp Type="addAsset" atGUID="100855">
<Asset>
            <Template>SlotFactoryBuilding7</Template>
            <Values>
                <Standard>
                    <Name>Clay_Cover</Name>
                    <GUID>newGUID added by modloader</GUID>
```
So the modloader would add the asset at Path="//Assets[Asset/Values/Standard/GUID='100855']" just like in the example mentioned earlier. Then we need to figure out which newGUID to add inside the <GUID> tag (I'd do that just by replacing whatever is inside that GUID tag, some user may like to type Karl-Heinz in there or something weird).
To figure out the new GUID I´d get all GUIDs currently in the game. (i did that with python for some testing earlier) like(attention: some of them are negative):
```
def find(substr, infile, outfile):
	cnt = 1
	with open(infile, encoding="utf8") as a, open(outfile, 'w') as b:
		for line in a:
			cnt += 1
			if substr in line:
				cut = line.split("<GUID>")
				cut = cut[1].split("</GUID>")
				b.write(cut[0])
				b.write("\n")
				print(cut[0])			
find('<GUID>', 'assets.xml', 'guids.xml')
```
then sort them like:
```
def sort(infile, outfile):
	guids = []
	with open(infile, encoding="utf8") as a, open(outfile, 'w') as b:
		for line in a:
			guids.append(int(line))
		guids.sort()
		for x in range(len(guids)):
			print(guids[x])
			b.write(str(guids[x]))
			b.write("\n")
				
sort('guids.xml', 'sorted_guids.xml')
```
now just determine the next integral number after 100855 that isn´t part of that list and obviously add that number to the list, so the next asset won´t get the same guid.

I would even allow to user to do something like: 
```
<ModOp Type="addAsset" atGUID="100855">
<Asset>
            <Template>SlotFactoryBuilding7</Template>
            <Values>
                <Standard>
                    <Name>Clay_Cover</Name>
                    <GUID>newGUID added by modloader</GUID>
                     rest of that asset...
<Asset>
            <Template>SlotFactoryBuilding7</Template>
            <Values>
                <Standard>
                    <Name>Clay_Cover</Name>
                    <GUID>newGUID added by modloader</GUID>
......                rest of that asset...
</ModOp>
```
so they can add multiple assets with new guids at the path of atGUID="100855"(//Assets[Asset/Values/Standard/GUID='100855'])

That's what I think to be a good solution. I did talk with some other guys about that and that´s whats the consensus was. Other opinions are very welcome.

**Comment by xforce** [comment] 2019-05-23 17:03
@kskudlik thanks for the nice write up.
Sounds like a nice addition and probably the easiest to use way, at least I don't see anything that could be improved here, unless we want to do stuff like 'copy and merge asset' command, which would allow people to create slightly adjusted versions of existing assets more easily, but not sure that makes any as sense as I have no idea how common something like that would be.

**Comment by xforce** [comment] 2019-05-26 01:48
As of 439f1723dabe0e882e0adf8fb231741dde446c34 there are now actual tests for quite a bit of the functionality. There is probably something missing, so I will go over those tests again and add anything that would be interesting.
Now that we have actual tests, I can be more confident adding new things and tweaking the xml operations without breaking things.

**Closed** 2019-12-24 16:12 UTC
Labels: good first issue, help wanted
