### ISSUE TITLE
Isn`t compatible with game version 13.2

### ISSUE THREAD

**Issue by killkounter** [xforce/anno1800-mod-loader#118] opened 2022-02-15 17:57 UTC
Wanted to play anno 1800 with mods and modloader isnt compatible anymore

**Comment by cursedsummoner** [comment] 2022-02-15 18:36
same as https://github.com/xforce/anno1800-mod-loader/issues/117

**Comment by xforce** [comment] 2022-02-15 18:47
Duplicate of #117

**Closed by xforce** 2022-02-15 18:47 UTC
