### ISSUE TITLE
Anno 1800 Is updated

### ISSUE THREAD

**Issue by Roggan88** [xforce/anno1800-mod-loader#152] opened 2022-05-04 14:39 UTC
Had an update on anno so my mod loader want me to update but there is no updated files :P 

Just wanted to let you know 👍

**Comment by xyrus02** [comment] 2022-05-06 18:49
Not sure if it all works reliably, but what I did is clone this repo, change `libs/python35/src/version.h`, change line 6 to:

     #define VERSION_REVISION            7

and build the DLL using Bazel.

Make sure you got VS2022 Community, Bazel (npm i -g @bazel/bazelisk) and python installed. If on Windows 10/11, disable the app alias in Apps & Features or otherwise it will open the Windows Store during build (lol)

If you don't know what I'm talking about, you probably have to wait for the update of this tool.

**Comment by Belyosd** [comment] 2022-05-09 15:07
@xyrus02  can you upload the DLL? tried it myself but im too stoopid

**Comment by xyrus02** [comment] 2022-05-09 15:31
There you go: 
Compiled DLL: [python35.zip](https://github.com/xforce/anno1800-mod-loader/files/8653109/python35.zip)
Hash: 73126ee5532c42bf05a292761566468a3b012b3ea16a864f47e6e812c2923886
Virus scan result: [VirusTotal](https://www.virustotal.com/gui/file/73126ee5532c42bf05a292761566468a3b012b3ea16a864f47e6e812c2923886/detection)

**Comment by 43Rageon** [comment] 2022-05-09 20:24
> There you go: Compiled DLL: [python35.zip](https://github.com/xforce/anno1800-mod-loader/files/8653109/python35.zip) 


Is it enough to copy and replace them in the relevant directory? I did that but it didn't work for me, where am I doing wrong?

**Comment by xyrus02** [comment] 2022-05-09 20:54
Yes it is enough, and I have no idea what you're doing wrong.

**Comment by 43Rageon** [comment] 2022-05-09 21:54
> Yes it is enough, and I have no idea what you're doing wrong. You probably think you did it but didn't actually do it. Double check and if it still doesn't work, wait for official release.

One of the files I have is listed as "python35_ubi.dll" so it may not be working?
When will the official version be released?

**Comment by xyrus02** [comment] 2022-05-10 07:37
That's probably just the original version of the file. I didn't replace it so in my folder, there is still the one from the 0.8.6 release. Maybe try set it up like that.

If I knew when the official release came out, I wouldn't have patched it myself lol. Could be any day but the maintainer is probably busy so need patience.

**Comment by ColdCactus** [comment] 2022-05-11 07:56
`That's probably just the original version of the file. I didn't replace it so in my folder, there is still the one from the 0.8.6 release. Maybe try set it up like that.`

I believe that's the case, however, the python35_ubi.dll hasn't been updated in the release package since late last year (I believe) and no longer works to restore the unmodded DLL for current versions.

Which is no big deal, having UPlay verify the game files will restore the current stock DLL even if you don't have it backed up (like me, carelessly).

**Comment by KarlThorsten89** [comment] 2022-05-11 23:09
Yeah, noe of this worked for me. I can't figure out what is wrong anymore. Maybe cuz I got most or all the DLC installed? And I got the original Anno 1800 release from Steam, so it runs through Steam as well as the Ubi launcher. Do I need to reinstall it from just the Ubi launcher to get this to work?

I got the new DLLs from last month, I've updated the Mod Manager, I've tried to run the game via the mod manager without mods, and the manager tells me either IT needs to be updated, or the DLL files from here need updating/replacing, and licking yes does nothing. I am just at a loss. Nothing wants to work.

And when it does 'launch', I see the Ubilauncher open that little load window before Anno 1800, and then either it appears again as when you exit the game, or it tells me again to update something, or I have the wrong game version, or the Anno1800 exe just self-quits in the task-manager, or stays stuck there, and nothing ever happens.
I am just lost.

**Comment by zhongyiwei** [comment] 2022-05-20 16:08
I am able to get inside the game with 0.8.6 mod loader, however, once I read my save, after waiting for 20 seconds it will crash to the desktop without showing any warning messages.
Not sure whether anyone else got it :(

**Comment by KarlThorsten89** [comment] 2022-05-21 14:32
Nope, it's back to not working or the game runs but the mods jsut never get loaded. So stuck again with an unmodded game.

**Comment by xyrus02** [comment] 2022-05-26 14:48
Today the "incompatible" message came back, proably because Anno updated again. I recompiled the Python DLL with version 0.8.8:

File: [python35.zip](https://github.com/xforce/anno1800-mod-loader/files/8779800/python35.zip)
Virustotal scan result: [Virustotal](https://www.virustotal.com/gui/file/35ddb29b17edf6f2017f5f8ede5058461ac6bdd39b38fa918518b35a6db0c6e1?nocache=1 )

**Comment by xforce** [comment] 2022-06-01 18:44
This is a rather complicated issue that won't be fixed by just bumping the version, the root cause is some weird interaction with the copy protection used in Anno (Denuvo), which results in certain memory scans to fail _sometimes_.
I haven't found a solution for this yet and this has been an issue for a long time, if someone has an ideas, please do tell.
This is still tracked in #51, thus closing this issue.

**Closed by xforce** 2022-06-01 18:44 UTC
