### ISSUE TITLE
in game buildings get lost

### ISSUE THREAD

**Issue by garignebean** [xforce/anno1800-mod-loader#144] opened 2022-04-15 20:56 UTC
modding with this version causes problems in the game like the fishery is gone ı cannot build the fisshery

**Comment by blastpv** [comment] 2022-04-16 11:57
the verification steps are simple.
1. rename the mods folder to any other name to disable the loading of mods
2. We check the game files.
3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)

**Comment by Nimfas31** [comment] 2022-04-16 14:26
> modding with this version causes problems in the game like the fishery is gone ı cannot build the fisshery

I have the same issue ...

**Comment by DoctorMikeska** [comment] 2022-05-10 18:45
Removed my mods from the folder, loaded up new game with just mod loader installed, fisheries, public mooring, and several mines and industries are missing. Removed mod loader and replaced the original python35.dll, loaded up a new game, fisheries were back. Conclusion, the mod loader is the issue, not the mods themselves, and as of now modding is not possible on my end.

**Comment by jakobharder** [comment] 2022-05-11 10:41
> Conclusion, the mod loader is the issue, not the mods themselves, and as of now modding is not possible on my end.

If the modloader were the issue, noone could play right now. But that's not the case. So far that issue was always fixed by mods updating their `IsMainFactory` fields.

**Comment by DoctorMikeska** [comment] 2022-05-11 21:16
> If the modloader were the issue, noone could play right now. But that's not the case. So far that issue was always fixed by mods updating their `IsMainFactory` fields.

How is the modloader not the issue, if the problems persist with ONLY the modloader installed, no mods? Maybe I'm just confused, but a mod cannot affect the game if the mod is not present.

I can still play the game, the game is not unplayable, missing goods aren't a huge roadblock and there IS a workaround. A total lack of mods isn't a deal breaker, I was merely pointing out that, on my end, the modloader alone is causing an issue.

**Comment by jakobharder** [comment] 2022-05-12 05:29
Pieces of mods remain in your savegame. Even if you delete the mods.

**Comment by DoctorMikeska** [comment] 2022-05-12 19:44
> Pieces of mods remain in your savegame. Even if you delete the mods.

I realise that, which is why I've reinstalled and started new games to test out which was causing an issue. Perhaps mods are also to blame, but on a clean install, new game with only the modloader python35.dll installed, the issue is present. I'm sure it will all be fixed in the next update, and in the meanwhile there are other, less fun, games to spend my time on.

**Comment by xforce** [comment] 2022-09-19 20:35
This has been long confirmed by many people to have been a mod related issue. Not a loader issue. Closing.

**Closed by xforce** 2022-09-19 20:35 UTC
