### ISSUE TITLE
old unsupported CPUs are not working, 0xc000142 (invalid instruction)

### ISSUE THREAD

**Issue by PhilB62** [xforce/anno1800-mod-loader#71] opened 2020-10-25 16:03 UTC
using modloader 7.12 I get problem code '0xc000142' message twice and game aborts

if I use modloader 7.10 the game starts and runs correctly but mods are no longer active, they were working correctly before the ubi update with this configuration

note that even if I remove all the mod files from the mods folder using 7.12 modloader the '0xc000142' message appears and game aborts as per above.  so the problem seems to exist in the modloader, not the mods themselves

**Comment by xforce** [comment] 2020-10-26 12:59
This error happens on CPUs outside of the Minimum System Requirements for Anno 1800.
Meaning that people running into this are using an unsupported system configuration.
There are currently no short-term (as in the next few days), to work on this.

I will leave this open for now and may consider this for 0.8, but there won't be a short term fix for 0.7.x.

**Comment by Fiber82** [comment] 2020-11-02 21:13
this keeps coming up 0xc00007b when I want to play the game please Help????

**Comment by Fiber82** [comment] 2020-11-02 21:13
dont know what to do

**Comment by Maifair-928** [comment] 2020-12-27 23:37
Hi xforce, 
I face the same issue since Game-Update 9.0 and Mod Loader version 0.7.12..
can´t start the game with Mod Loader and Mods Folder.

Bevor Mod Loader 0.7.10 worked just fine with diffrent Mods.

Any solution for this issue jet? 
Thank you.

**Comment by Nicholas-Steel** [comment] 2021-01-16 10:26
> 
> 
> Hi xforce,
> I face the same issue since Game-Update 9.0 and Mod Loader version 0.7.12..
> can´t start the game with Mod Loader and Mods Folder.
> 
> Bevor, Mod Loader 0.7.10 worked just fine with diffrent Mods.
> 
> My System:
> OS: Microsoft Windows 10, 64-bit Professional (build 19041)
> CPU: AMD Phenom(tm) II X4 965 Processor
> GPU: AMD Radeon 5500 XT
> RAM: 16384 MB
> 
> Any solution for this issue jet?
> Thank you.

See XForce's message, it explains what the problem is and when you can expect a potential solution. Ideally you'd upgrade your computer hardware to meet the minimum specifications listed for the game.

**Comment by andbile** [comment] 2021-02-14 19:54
I hope you will have the time to fix this bug.
My System:
OS: Microsoft Windows 10, 64-bit Professional (20h2)
CPU: Xeon E5440
GPU: GeForce 750ti
RAM: 8 GB

**Comment by xforce** [comment] 2021-02-22 19:14
This will be fixed in 0.8.0

**Closed by xforce** 2021-02-22 19:14 UTC
